name: Runs CI on PR

on: pull_request

jobs:
  ci:
    name: Runs CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: yarn

      # - name: Run Tests
      #   run: yarn test --coverage

      - name: Run Linting
        run: yarn lint

      - name: Run Build
        run: yarn build

      - name: Check Commit Message
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: .commitlintrc.json
