name: Runs CI on PR

on: pull_request

jobs:
  ci:
    name: Runs CI
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Runs CI and Build
        run: npm ci && npm run build
